### PR TITLE
Created APIs for dynamic list of user type, user status, and badge type

### PR DESCRIPTION
**Pull request by at3362**

### CODE REVIEW

**Review by Muthunatesan — CHANGES_REQUESTED** [review]
All looks good,Method type should be GET as there is no post operations involved

**Comment by at3362** [comment]
Method type updated to "GET"

**Review by Muthunatesan — CHANGES_REQUESTED** [review]
methods type are changed again to POST

**Comment by Muthunatesan** [comment]
Merge the pull request #7

**Pull request merged**
